/*
 * VOICEVOX Engine
 *
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.0-preview.12
 *
 * Generated by: https://openapi-generator.tech
 */

/// DownloadableLibrary : ダウンロード可能な音声ライブラリの情報（最新情報をwebで取得することを考慮して、ローカルの情報はない）

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DownloadableLibrary {
    #[serde(rename = "download_url")]
    pub download_url: String,
    #[serde(rename = "bytes")]
    pub bytes: i32,
    #[serde(rename = "speaker")]
    pub speaker: Option<Box<crate::models::Speaker>>,
    #[serde(rename = "speaker_info")]
    pub speaker_info: Option<Box<crate::models::SpeakerInfo>>,
}

impl DownloadableLibrary {
    /// ダウンロード可能な音声ライブラリの情報（最新情報をwebで取得することを考慮して、ローカルの情報はない）
    pub fn new(
        download_url: String,
        bytes: i32,
        speaker: Option<crate::models::Speaker>,
        speaker_info: Option<crate::models::SpeakerInfo>,
    ) -> DownloadableLibrary {
        DownloadableLibrary {
            download_url,
            bytes,
            speaker: speaker.map(Box::new),
            speaker_info: speaker_info.map(Box::new),
        }
    }
}
