/*
 * VOICEVOX Engine
 *
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.0-preview.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LicenseInfo : 依存ライブラリのライセンス情報



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LicenseInfo {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "license", skip_serializing_if = "Option::is_none")]
    pub license: Option<String>,
    #[serde(rename = "text")]
    pub text: String,
}

impl LicenseInfo {
    /// 依存ライブラリのライセンス情報
    pub fn new(name: String, text: String) -> LicenseInfo {
        LicenseInfo {
            name,
            version: None,
            license: None,
            text,
        }
    }
}


