/*
 * VOICEVOX Engine
 *
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.0-preview.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Mora : モーラ（子音＋母音）ごとの情報



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Mora {
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "consonant", skip_serializing_if = "Option::is_none")]
    pub consonant: Option<String>,
    #[serde(rename = "consonant_length", skip_serializing_if = "Option::is_none")]
    pub consonant_length: Option<f32>,
    #[serde(rename = "vowel")]
    pub vowel: String,
    #[serde(rename = "vowel_length")]
    pub vowel_length: f32,
    #[serde(rename = "pitch")]
    pub pitch: f32,
}

impl Mora {
    /// モーラ（子音＋母音）ごとの情報
    pub fn new(text: String, vowel: String, vowel_length: f32, pitch: f32) -> Mora {
        Mora {
            text,
            consonant: None,
            consonant_length: None,
            vowel,
            vowel_length,
            pitch,
        }
    }
}


