/*
 * VOICEVOX Engine
 *
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.0-preview.12
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MorphableTargetInfo {
    #[serde(rename = "is_morphable")]
    pub is_morphable: bool,
}

impl MorphableTargetInfo {
    pub fn new(is_morphable: bool) -> MorphableTargetInfo {
        MorphableTargetInfo {
            is_morphable,
        }
    }
}


