/*
 * VOICEVOX Engine
 *
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.0-preview.12
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParseKanaBadRequest {
    #[serde(rename = "text")]
    pub text: String,
    /// |name|description| |---|---| | UNKNOWN_TEXT | 判別できない読み仮名があります: {text} | | ACCENT_TOP | 句頭にアクセントは置けません: {text} | | ACCENT_TWICE | 1つのアクセント句に二つ以上のアクセントは置けません: {text} | | ACCENT_NOTFOUND | アクセントを指定していないアクセント句があります: {text} | | EMPTY_PHRASE | {position}番目のアクセント句が空白です | | INTERROGATION_MARK_NOT_AT_END | アクセント句末以外に「？」は置けません: {text} | | INFINITE_LOOP | 処理時に無限ループになってしまいました...バグ報告をお願いします。 |
    #[serde(rename = "error_name")]
    pub error_name: String,
    #[serde(rename = "error_args")]
    pub error_args: ::std::collections::HashMap<String, String>,
}

impl ParseKanaBadRequest {
    pub fn new(text: String, error_name: String, error_args: ::std::collections::HashMap<String, String>) -> ParseKanaBadRequest {
        ParseKanaBadRequest {
            text,
            error_name,
            error_args,
        }
    }
}


