/*
 * VOICEVOX Engine
 *
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.0-preview.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SpeakerSupportPermittedSynthesisMorphing : An enumeration.

/// An enumeration.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpeakerSupportPermittedSynthesisMorphing {
    #[serde(rename = "ALL")]
    ALL,
    #[serde(rename = "SELF_ONLY")]
    SELFONLY,
    #[serde(rename = "NOTHING")]
    NOTHING,

}

impl ToString for SpeakerSupportPermittedSynthesisMorphing {
    fn to_string(&self) -> String {
        match self {
            Self::ALL => String::from("ALL"),
            Self::SELFONLY => String::from("SELF_ONLY"),
            Self::NOTHING => String::from("NOTHING"),
        }
    }
}




