/*
 * VOICEVOX Engine
 *
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.0-preview.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SpeakerInfo : 話者の追加情報



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpeakerInfo {
    #[serde(rename = "policy")]
    pub policy: String,
    #[serde(rename = "portrait")]
    pub portrait: String,
    #[serde(rename = "style_infos")]
    pub style_infos: Vec<crate::models::StyleInfo>,
}

impl SpeakerInfo {
    /// 話者の追加情報
    pub fn new(policy: String, portrait: String, style_infos: Vec<crate::models::StyleInfo>) -> SpeakerInfo {
        SpeakerInfo {
            policy,
            portrait,
            style_infos,
        }
    }
}


