/*
 * VOICEVOX Engine
 *
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.0-preview.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SupportedFeatures : エンジンが持つ機能の一覧



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SupportedFeatures {
    #[serde(rename = "adjust_mora_pitch")]
    pub adjust_mora_pitch: bool,
    #[serde(rename = "adjust_phoneme_length")]
    pub adjust_phoneme_length: bool,
    #[serde(rename = "adjust_speed_scale")]
    pub adjust_speed_scale: bool,
    #[serde(rename = "adjust_pitch_scale")]
    pub adjust_pitch_scale: bool,
    #[serde(rename = "adjust_intonation_scale")]
    pub adjust_intonation_scale: bool,
    #[serde(rename = "adjust_volume_scale")]
    pub adjust_volume_scale: bool,
    #[serde(rename = "interrogative_upspeak")]
    pub interrogative_upspeak: bool,
    #[serde(rename = "synthesis_morphing")]
    pub synthesis_morphing: bool,
}

impl SupportedFeatures {
    /// エンジンが持つ機能の一覧
    pub fn new(adjust_mora_pitch: bool, adjust_phoneme_length: bool, adjust_speed_scale: bool, adjust_pitch_scale: bool, adjust_intonation_scale: bool, adjust_volume_scale: bool, interrogative_upspeak: bool, synthesis_morphing: bool) -> SupportedFeatures {
        SupportedFeatures {
            adjust_mora_pitch,
            adjust_phoneme_length,
            adjust_speed_scale,
            adjust_pitch_scale,
            adjust_intonation_scale,
            adjust_volume_scale,
            interrogative_upspeak,
            synthesis_morphing,
        }
    }
}


