/*
 * VOICEVOX Engine
 *
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.0-preview.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SupportedDevicesInfo : 対応しているデバイスの情報



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SupportedDevicesInfo {
    #[serde(rename = "cpu")]
    pub cpu: bool,
    #[serde(rename = "cuda")]
    pub cuda: bool,
    #[serde(rename = "dml")]
    pub dml: bool,
}

impl SupportedDevicesInfo {
    /// 対応しているデバイスの情報
    pub fn new(cpu: bool, cuda: bool, dml: bool) -> SupportedDevicesInfo {
        SupportedDevicesInfo {
            cpu,
            cuda,
            dml,
        }
    }
}


