/*
 * VOICEVOX Engine
 *
 * VOICEVOXの音声合成エンジンです。
 *
 * The version of the OpenAPI document: 0.14.0-preview.12
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UpdateInfo : エンジンのアップデート情報



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateInfo {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "descriptions")]
    pub descriptions: Vec<String>,
    #[serde(rename = "contributors", skip_serializing_if = "Option::is_none")]
    pub contributors: Option<Vec<String>>,
}

impl UpdateInfo {
    /// エンジンのアップデート情報
    pub fn new(version: String, descriptions: Vec<String>) -> UpdateInfo {
        UpdateInfo {
            version,
            descriptions,
            contributors: None,
        }
    }
}


